### ISSUE TITLE
Favicons issue

### ISSUE THREAD

**Issue by lavaloch** [lewagon/lewagon#7]
Favicons of lewagon.com, kitt.lewagon.org and karr.lewagon.org are not the same and don't have the same size. 
<img width="176" alt="screen shot 2017-04-28 at 6 35 03 pm" src="https://cloud.githubusercontent.com/assets/26142228/25538074/875f5c0c-2c41-11e7-9cdc-bee4af7fe190.png">
#DevilIsInDetails

**Comment by ssaunier** [comment]
Thanks for reporting! It's been fixed for www and Kitt (Karr will be sunset soon)
